source: 
  type: file
  path: C:\Users\Jose\go\src\dev\readyamltest\testfiles\xlsx\test.xlsx
  extension: xlsx
destination: 
  type: db
  table: webservice.evo_firmados_sf_v2
  structure: 
   - Producto
   - ID_Cliente_EVO 
   - Fecha_de_creacion 
   - Estado_cliente 
   - Ultimo_punto_de_abandono 
   - Gestion_Captacion 
   - Numero_del_proceso_de_contratacion 
   - Estado 
   - Motivo_desestimacion 
   - Numero_de_Logalty 
   - ID_Persona_Iris 
   - Numero_Expediente 
   - Clase_de_Cliente 
   - Fecha_de_firma 
   - Tipo_de_identificacion 